### PR TITLE
Create fjm-Philadelphia.md file

### PR DESCRIPTION
**Pull request by fjmurray**
Create a file titled 'fjm-Philadelphia.md' detailing places to eat
and places to see and visit in Philadelphia.

Want to get it reviewed.

Add things to skip.

### CODE REVIEW

**Comment by desireedickerson** [comment]
@fjmurray what is the best pizza place? :pizza:

**Comment by nvrdftd** [comment]
@fjmurray I was studying in the University city. I really liked the Art Museum, and of course, cheesesteak. 💯

**Comment by fjmurray** [comment]
@desireedickerson "Revolution House" on Market Street is highly regarded.

**Comment by fjmurray** [comment]
@nvrdftd Awesome.  👍

**Pull request merged**
