### PR TITLE
Create lasea-miami.md

### PR DESCRIPTION
**Pull request by khallai**
Added some places and stuff. 💯  USA Slay all Day!! Rio2016

### CODE REVIEW

**Comment by zorroborg** [comment]
@khallai wish I was in Miami! 👍

**Comment by githubteacher** [comment]
@khallai What is your favorite 🍺 at Funky Buddha? Have you ever had Cigar City Brewing 🍻 ?

**Comment by zorroborg** [comment]
@khallai I accidently closed then repopened..  wish I was in Miami

**Comment by khallai** [comment]
@githubteacher the floridian is a classic! Never been to Cigar city but i'll put it on my list 👍 @zorroborg it's always beautiful in Miami, come by any time!

**Pull request merged**
